// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qnbeecizneeaznhbcuzm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFuYmVlY2l6bmVlYXpuaGJjdXptIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDM0MjU1MjQsImV4cCI6MjA1OTAwMTUyNH0.Qw1fLKqbJltv0NfKZT2_tCRzcWlZevmi2r8Vjs9CfR8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);